# Generated by Django 5.2.4 on 2025-08-31 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_of_measure', models.CharField(choices=[('PCS', 'Pieces (PCS)'), ('KG', 'Kilograms (KG)'), ('G', 'Grams (G)'), ('M', 'Meters (M)'), ('CM', 'Centimeters (CM)'), ('L', 'Liters (L)'), ('ML', 'Milliliters (ML)')], max_length=3)),
                ('version', models.CharField(blank=True, max_length=64)),
                ('variant', models.CharField(blank=True, max_length=64)),
                ('state_of_supply', models.CharField(choices=[('RAW', 'Raw Material'), ('WIP', 'Work in Progress'), ('FG', 'Finished Goods'), ('SFG', 'Semi Finished'), ('CONS', 'Consumable')], max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['make', 'model'], name='devices_dev_make_id_775d8c_idx')],
            },
        ),
    ]
