# Generated by Django 5.2.4 on 2025-08-31 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='devices_dev_make_id_775d8c_idx',
        ),
        migrations.RemoveField(
            model_name='device',
            name='make',
        ),
        migrations.AddField(
            model_name='device',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='make_id',
            field=models.ForeignKey(default=1, help_text='Manufacturer of the device', limit_choices_to={'role__key__iexact': 'manufacturer'}, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='mrp',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='state_of_supply',
            field=models.CharField(choices=[('RAW_MATERIAL', 'Raw Material'), ('WORK_IN_PROGRESS', 'Work in Progress'), ('FINISHED_GOODS', 'Finished Goods'), ('SEMI_FINISHED', 'Semi-Finished'), ('CONSUMABLE', 'Consumable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='unit_of_measure',
            field=models.CharField(choices=[('PCS', 'Pieces (PCS)'), ('KG', 'Kilograms (KG)'), ('G', 'Grams (G)'), ('M', 'Meters (M)'), ('CM', 'Centimeters (CM)'), ('L', 'Liters (L)'), ('ML', 'Milliliters (ML)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='variant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='device',
            table='devices',
        ),
    ]
