# Generated by Django 5.2.5 on 2025-09-01 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Total quantity for this device BOM', null=True),
        ),
        migrations.CreateModel(
            name='BOMEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_mark', models.CharField(blank=True, max_length=255, null=True)),
                ('components_required', models.CharField(blank=True, max_length=255, null=True)),
                ('designator', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_qty', models.PositiveIntegerField(default=0)),
                ('fp_cross_checked', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_entries', to='devices.device')),
            ],
            options={
                'verbose_name': 'BOM Entry',
                'verbose_name_plural': 'BOM Entries',
                'db_table': 'device_bom_entries',
                'ordering': ['created_at'],
            },
        ),
    ]
