# Generated by Django 5.2.5 on 2025-09-01 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_quantity_bomentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=100)),
                ('length', models.DecimalField(decimal_places=2, help_text='in mm', max_digits=10)),
                ('breadth', models.DecimalField(decimal_places=2, help_text='in mm', max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, help_text='in mm', max_digits=10)),
                ('color', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enclosure', to='devices.device')),
                ('make', models.ForeignKey(help_text='Manufacturer of the enclosure', limit_choices_to={'role__key__iexact': 'manufacturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enclosures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_enclosures',
                'ordering': ['-created_at'],
            },
        ),
    ]
