# Generated by Django 5.2.5 on 2025-09-01 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_enclosure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WireHarness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=100)),
                ('no_of_wires', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('length', models.DecimalField(decimal_places=2, help_text='in mm', max_digits=10)),
                ('no_of_connectors', models.PositiveIntegerField()),
                ('pin_type', models.CharField(choices=[('1_PIN', '1 Pin'), ('2_PIN', '2 Pin'), ('3_PIN', '3 Pin'), ('4_PIN', '4 Pin'), ('5_PIN', '5 Pin'), ('6_PIN', '6 Pin'), ('7_PIN', '7 Pin'), ('8_PIN', '8 Pin'), ('9_PIN', '9 Pin'), ('10_PIN', '10 Pin')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wire_harness', to='devices.device')),
                ('make', models.ForeignKey(help_text='Manufacturer of the wire harness', limit_choices_to={'role__key__iexact': 'manufacturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wire_harnesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_wire_harnesses',
                'ordering': ['-created_at'],
            },
        ),
    ]
