# Generated by Django 5.2.5 on 2025-09-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_wireharness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wireharness',
            name='pin_type',
            field=models.CharField(choices=[('1 PIN', '1 Pin'), ('2 PIN', '2 Pin'), ('3 PIN', '3 Pin'), ('4 PIN', '4 Pin'), ('5 PIN', '5 Pin'), ('6 PIN', '6 Pin'), ('7 PIN', '7 Pin'), ('8 PIN', '8 Pin'), ('9 PIN', '9 Pin'), ('10 PIN', '10 Pin')], max_length=10),
        ),
    ]
