# Generated by Django 5.2.5 on 2025-09-02 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_alter_wireharness_pin_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wireharness',
            name='pin_type',
            field=models.CharField(choices=[('1 Pin', '1 Pin'), ('2 Pin', '2 Pin'), ('3 Pin', '3 Pin'), ('4 Pin', '4 Pin'), ('5 Pin', '5 Pin'), ('6 Pin', '6 Pin'), ('7 Pin', '7 Pin'), ('8 Pin', '8 Pin'), ('9 Pin', '9 Pin'), ('10 Pin', '10 Pin')], max_length=10),
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=100)),
                ('capacity', models.CharField(help_text='e.g., 850 mAH, 2000 mAh', max_length=50)),
                ('length', models.DecimalField(decimal_places=2, help_text='in mm', max_digits=10)),
                ('breadth', models.DecimalField(decimal_places=2, help_text='in mm', max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, help_text='in mm', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battery', to='devices.device')),
                ('make', models.ForeignKey(help_text='Manufacturer of the battery', limit_choices_to={'role__key__iexact': 'manufacturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batteries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Batteries',
                'db_table': 'device_batteries',
                'ordering': ['-created_at'],
            },
        ),
    ]
