# Generated by Django 5.2.5 on 2025-09-02 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_alter_wireharness_pin_type_battery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=100)),
                ('total_length', models.DecimalField(decimal_places=2, help_text='Total length at the set (in mm)', max_digits=10)),
                ('quantity_per_set', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sos_button', to='devices.device')),
                ('make', models.ForeignKey(help_text='Manufacturer of the SOS Button', limit_choices_to={'role__key__iexact': 'manufacturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_buttons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_sos_buttons',
                'ordering': ['-created_at'],
            },
        ),
    ]
