# Generated by Django 5.2.5 on 2025-09-02 05:43

import devices.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_sosbutton'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('part_no', models.CharField(max_length=100)),
                ('length', models.DecimalField(decimal_places=2, help_text='in mm', max_digits=10)),
                ('breadth', models.DecimalField(decimal_places=2, help_text='in mm', max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('sticker_image', models.ImageField(upload_to=devices.models.get_sticker_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sticker', to='devices.device')),
                ('make', models.ForeignKey(help_text='Manufacturer of the sticker', limit_choices_to={'role__key__iexact': 'manufacturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stickers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_stickers',
                'ordering': ['-created_at'],
            },
        ),
    ]
