# Generated by Django 5.2.5 on 2025-08-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_state_created_at_state_status_state_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ifsc',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linked_to_distributor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='linked_to_manufacturer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pan',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/pan/'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
