# Generated by Django 5.2.5 on 2025-08-30 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_district_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manufacturers',
            field=models.ManyToManyField(blank=True, related_name='partners_with', to=settings.AUTH_USER_MODEL),
        ),
    ]
